### ISSUE TITLE
Layout Not Being Appllied Correctly & Just Shows {{contents}}

### ISSUE THREAD

**Issue by washere** [AVGP/susi#10]
Layout is being applied but with curly brackets!
I tried many many things but still the output looks like:

```

. Home
. Projects
. Contact

{title}
{{date}}
{{contents}}
```

Even when applying the sample code from homepage:

```
{
  "title": "My Site",
  "date": "2014-11-27"
}

---

# Some headline

Some *text* of mine.
```

Layout is being applied but the input files contents are not imported!
I tried various parameters in command line, renaming layout file & where it goes, folder paths etc.
Any ideas?

If I do not apply layout, the files are output correctly as html files perfectly!

**Comment by washere** [comment]
Seems a bug with layout paths!
If I leave out folder paths to layout, it works.

So, Where in & out & layout, are my folders:

`susi in out layout/page.html
`

generates files but gives error as in top post.

```
. Home
. Projects
. Contact

{title}
{{date}}
{{contents}}
```

if we try other conventions for layout path, it gives errors, no output generated.

If I put the full path, eg:

susi in out `/home/mypc/Documents/Static-Gens/susi/layout/page.html
`

It generates but still the output is without actual content, just the layout as in top post.

If i have layout as:
`
/susi/layout/page.html`

and type:

`susi in out
`

It outputs ok but the formatting includes { } etc.

So Leave out the layout path & file !
Also leave out other text in frontmatter.

so:

susi in out

from:

```
---
  "title": "My Site",
  "date": "2014-11-27"
---

# Some headline

Some *text* of mine.
```

Gives:

```
__________________________________________
"title": "My Site",
"date": "2014-11-27"
Some headline

Some text of mine.
```

So there is this bug & i can only go with default  layout/page.html to make it work and omit layout parameter!

Anyway seems dev is not around for some years, so  closing this.
Best wishes.

**Comment by AVGP** [comment]
If you want to give it a go and fix it, be my guest.

I would just use one of the many available, modern static site generators around.

**Comment by washere** [comment]
Thanks buddy, I already am. 
https://jamstack.org/generators/
