### ISSUE TITLE
Can you make clear the license?

### ISSUE THREAD

**Issue by ifraixedes** [AVGP/susi#3]
Hi,

I know that the license of this repository is ISC, because appears inside `pacakge.json`, nonetheless it would be good if you can a LICENSE file and/or a note in the README, because it would be clearer.

Thanks.

**Comment by AVGP** [comment]
Thanks for bringing this up. I will  add a license file and remark to the README when I am on a computer. 

Quick question: what kept you from submitting a pull request for your suggestion? 
Can I do something to encourage you to submit a patch or is this repository missing information on how to submit a pull request? 

I am keen on improving the project so people feel empowered. Any feedback welcome!

**Comment by ifraixedes** [comment]
> Thanks for bringing this up. I will add a license file and remark to the README when I am on a computer.

It's OK, no problem at all; it was more a suggestion.

> Quick question: what kept you from submitting a pull request for your suggestion? 

Being honest, nothing, it had been an improvement or type, I had done it, however in this case I didn't see appropriated to send a PR for the LICENSE, I don't know exactly your full name, if you want to add email address, and so on; moreover I don't know if you wanted to add in the README and/or LICENSE file.

> Can I do something to encourage you to submit a patch or is this repository missing information on how to submit a pull request?

I'm not sure, I don't have nothing to provide so far.

> I am keen on improving the project so people feel empowered. Any feedback welcome!

The only idea which I have is  to add a section in the README about contributing.

**Comment by AVGP** [comment]
Alright, cool. I've added the LICENSE and a contributing section as well.

Thanks and have fun!
