### ISSUE TITLE
only read .md files

### ISSUE THREAD

**Issue by pekeler** [AVGP/susi#4]
After going through the paralyzing number of choices on staticsitegenerators.net and spending too much time getting some of the popular choices working, susi turns out to be exactly what I need. The only thing that has bothered me so far is that susi crashes if the input-directory includes non-markdown files. I think it would be nice if it only tried to read .md files.

**Comment by AVGP** [comment]
Hey @pekeler - happy to hear that SuSi is just the right thing for you, too!

I'm surprised by this bug as SuSi actually should skip over everything that doesn't have ".md" as the extension.

To make sure I can resolve the situation quickly, can you help me out a bit by telling me:

* Does that also happen, when there's a non-markdown textfile in the input directory?
* Does it work when you move all your non-markdown files out of the input directory (just double checking here)?
* What files is it seeing that crash it? Images?

**Comment by pekeler** [comment]
Uh, sorry. I thought it I had this problem last night but now it's behaving exactly like you say. I guess I just had an empty .md file. And I'm OK if it crashes in that case.

**Comment by AVGP** [comment]
I just saw that it actually crashes quite recklessly when the Frontmatter
part of the file is missing - it should be *much* friendlier in that case,
will patch :-)

Thanks for reporting the issue!

2015-06-30 23:58 GMT+02:00 Christian Pekeler <notifications@github.com>:

**Comment by AVGP** [comment]
SuSi 0.2.3 gives a nicer error message now. Again, thanks for reporting this bug!

**Comment by pekeler** [comment]
Cool!
I remembered my exact problem: my input-directory is a separate git-repo with all the md-files at the root level plus the README.md which doesn't have the Frontmatter and therefore caused the crash.

**Comment by AVGP** [comment]
Ahhh, that makes sense. Still - it should have handled it in a more user-friendly way. And it now does.
